server:
  port: 8089

spring:
  profiles:
    active: test
  swagger:
    enabled: true
    title: 标题
    description: 描述信息
    version: 1.0.0
    contact:
      name: sundog
    base-package: swagger扫描的基础包，默认：全扫描(分组情况下此处可不配置)
    #全局参数,比如Token之类的验证信息可以全局话配置
    global-operation-parameters:
      - description: 'Token信息,必填项'
        modelRef: 'string'
        name: 'Authorization'
        par ameter-type: 'header'
        required: true
    groups:
      basic-group:
        base-package: com.yukong.chapter6.controller
      system-group:
        base-package: com.battcn.controller.system
    #登录信息
    security:
      username: sundog
      password: 123456
#      filter-plugin: true

#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  typeAliasesPackage: com.yukong.chapter6.entity
  global-config:
    id-type: 0
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    logic-delete-value: -1
    logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    call-setters-on-nulls: true